### ISSUE TITLE
Workshop Lisbon Feedback

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/components-catalog#194]
We didn't get much feedback about the from the workshop itself since the attendance was low so here some of own feedback:

### High number of metamask interactions

The biggest issue so far is the amount of metamask operations required to published an asset. At most we should only require two metamask operations to publish an asset (signature to generate the DDO proof and the actual call to the DIDRegistry to register the asset on chain.

Currently by default we end up with 5 or 6 metamask operations. Most of them come from `approval` calls.
The component catalog should check if an address already gave permissions (transfer nfts, spend some funds, ...) before requesting the user to give approval again.

### Better naming for some methods

We should improve a least some method names to be more intuitive. For instance right now in order to buy an NFT we need to call `subscriptions.buySubscription` which is very confusing when I just want to buy an NFT.

### Check the defaults being used by the provided methods

For example when publishing an NFT `preMint` defaults to `false` which I think is correct and is the same default used by the sdk. The problem is that by default in the catalog we are not giving the `transferNFTCondition` permissions to mint so the `nft-transfer` call to the gateway will always fail unless the NFTs are pre mintend.

### Oauth tokens

When we decided to use oauth for the gateway we implemented it in such a way that it was hidden from the user. The way the gateway + sdk works is:
- The user needs to make an authenticated call to the gateway
- The sdk checks if a token exists and if not creates one

With the catalog we decided to expose that functionality directly to the user:
- we have `marketplaceAuthToken` in the skd config settings
- we have methods like `account.generateToken` and `acount.login` that are confusing.
- `account` in this case is the name of a module of the catalog an not an actual account which makes things double confusing. When using the catalog I still struggle to understand the difference between `account` and what is returned by `getCurrentAccount`.

I think the best solution here is to have a `Login` or `Connect to Nevermined` interface that takes care generating the correct tokens for both the gateway and the marketplace api. This is more intuitive because everyone that has used dapps before are used to first connecting their wallet before they can use the app.

### Metamask interactions

Right now we don't provide any feedback about what is happening every time metamask wants something. We need to see if there is a better way to present messages to the user through metamask
![Screenshot from 2022-11-04 16-02-56](https://user-images.githubusercontent.com/1793187/200007783-ea74ced7-1f1b-4e9d-beec-05abc29892f0.png)

We also have some interactions that look very scary and scammy and it was pointed out during the workshop
![Screenshot from 2022-11-04 16-06-08](https://user-images.githubusercontent.com/1793187/200008408-13a2c571-36e1-4ff4-aca1-b1e64d14fa25.png)

### The catalog doesn't always use the correct account

The catalog will always try to use an account that is connected regardless of the account that is currently chosen in metamask. To reproduce:

1. Select a metamask account and connect to the app
2. Through metamask switch to an account that is not connected
3. `getCurentAccount` will always return the address of the account that is connected regardless of the account currently chosen in metamask

### If Nevermined can be deployed in Solana
One of the questions that people were asking frequently is if Nevermined is deployed or can be used in Solana

**Comment by aaitor** [comment]
Validate with @r-marques that new catalog implementation fixes everything

**Comment by dancespiele** [comment]
## High number of metamask interations
I checked SDK but I cannot see that is calling to sign theses two contracts:
```ts
const transferNftConditionContractReceipt = await sdk.nfts.setApprovalForAll(transferNftCondition.address, true, accountWallet)
const gateawayContractReceipt = await sdk.nfts.setApprovalForAll(gatewayAddress, true, accountWallet)
```
with version 5.0 `setApprovalForAll` in 1155 on the sdk check if was approved before to avoid ask again. However to publish there are still theses interactions
1. sign markeplace api
2. sign gateway
3. sign contract interaction 0x3Dc23223C58A6eBb339e9975c33F31eA93453492 2 times
4. sign contract interaction
0x34226Ff38dC4eDAEe62083260B0F410f7Cc5c767

## Better naming for some methods
The method `subscriptions.buySubscription` is renamed to `nfts.access`

## Oauth tokens
With the new version of Catalog, developer doesn't need to deal with the authorization anymore, Catalog do it behind the scene

## Metamask interactions
Catalog provider shouldn't deal with UI, clients should do as Defi Marketplace is doing, anyway with the integration of `ConnectKit` should be easier to implement theses messages
About the warning message you will see in other dapps when you sign a contract giving to it the permission to do operation with your tokens or NFTS I don't think that we can do anything about it

## The catalog doesn't always use the correct account
With the integration of `ConnectKit` in Catalog provider (v0.5.0) should resolve that issue

**Comment by r-marques** [comment]
Blocked by https://github.com/nevermined-io/workshop/issues/17

**Comment by dancespiele** [comment]
Here is the PR https://github.com/nevermined-io/workshop/pull/18

**Comment by r-marques** [comment]
Tasks:
- [ ] The catalog doesn't always use the correct account:  If I switch to an account that is not connected in metamask the catalog will always try to use the first account that is connected. This is not the correct behavior
- [x] High number of metamask interations
- [ ] Oauth tokens: We should not need to handle that from the sdk side also
> Create and epic to:
> - Use the same oauth setup in both the gateway and marketplace api
> - handle those tokens internally on the sdk. this methods don't need to be exposed to the user
- [x] Better naming for some methods
- [ ] Check the defaults being used by the provided methods
> - publishNFT1155 does not use the defaults as the sdk. For instance https://github.com/nevermined-io/components-catalog/blob/5d4b912428cf2c9b69dae188d8da8c550376f3ae/lib/src/services/asset.tsx#L360 and https://github.com/nevermined-io/sdk-js/blob/master/src/nevermined/Assets.ts#L482
