### ISSUE TITLE
Connect button not working as expected

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/components-catalog#216]
1. The `connectkit` button provided by `nevermined-catalog` won't show the list of accounts to choose from and instead it uses the currently connected one
2. Sometimes user is not able to disconnect the account and is presented with the connectors list instead which doesn't work because the user is already connected. After page refresh user is able to disconnect:

https://user-images.githubusercontent.com/1643399/203293300-3d877ada-de97-4f15-a871-0ebba2dc9dd0.mov

**Comment by metabacalhau** [comment]
The issues have been addressed in the Nevermined One repo
