### ISSUE TITLE
Subgraph error Cannot read properties of undefined (reading '_meta')

### ISSUE THREAD

**Issue by dancespiele** [nevermined-io/components-catalog#236]
## Describe the bug
Running integration tests [related with the subgraph](https://github.com/nevermined-io/components-catalog/blob/develop/lib/integration-subgraph/subgraph.spec.tsx), several of them fail with this error `TypeError: Cannot read properties of undefined (reading '_meta')`, the error happens in `sdk-js`, see more [here](https://github.com/nevermined-io/sdk-js/blob/develop/src/events/SubgraphEvent.ts#L60)  

## To Reproduce

1. yarn install
2. run [tools](https://github.com/nevermined-io/tools)

## Expected behavior

The tests shouldn't fail with the error described above

**Comment by r-marques** [comment]
just released the sdk rc19 that should fix this issue

**Comment by dancespiele** [comment]
having the last version of `sdk` `rc20` and running the last version of graph `0.5.0` I get the same issue:
```
TypeError: Cannot read properties of undefined (reading '_meta')

      at SubgraphEvent.<anonymous> (node_modules/@nevermined-io/nevermined-sdk-js/src/events/SubgraphEvent.ts:60:33)
```

**Comment by dancespiele** [comment]
The tests failing with the same error are:
* https://github.com/nevermined-io/components-catalog/blob/develop/lib/integration-subgraph/subgraph.spec.tsx#L206
* https://github.com/nevermined-io/components-catalog/blob/develop/lib/integration-subgraph/subgraph.spec.tsx#L171
* https://github.com/nevermined-io/components-catalog/blob/develop/lib/integration-subgraph/subgraph.spec.tsx#L242

I start legacy code like this:
```bash
export KEEPER_VERSION=v3.0.0
export SUBGRAPH_VERSION=v0.5.0
./start_nevermined.sh --no-node --geth
```
I use node locally with branch `develop` and there I don't get any error in all the operations create, transfer and download asset

To start the tests, I execute `yarn test:subgraph`
