### ISSUE TITLE
catalog should use the sdk for the oauth logic instead of creating its own

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/components-catalog#240]
The catalog should use the `EthSignJWT` from the sdk https://github.com/nevermined-io/sdk-js/blob/develop/src/nevermined/utils/JwtUtils.ts#L7

**Comment by dancespiele** [comment]
We use ETHSignJWT [here](https://github.com/nevermined-io/components-catalog/blob/develop/lib/src/utils/marketplace_token.ts#L39)
